apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: podcustomizer.kuberneddies.dev
spec:
  group: kuberneddies.dev
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                promote:
                  type: bool
            status:
              type: object
              properties:
                numPromoted:
                  type: int64
                numDestroyed:
                  type: int64
                observedGeneration:
                  type: integer
                  format: int64
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: promoted
          type: bool
          jsonPath: .spec.promoted
        - name: numPromoted
          type: int64
          jsonPath: .status.numPromoted
        - name: numDestroyed
          type: in64
          jsonPath: .status.numDestroyed
  scope: Namespaced
  names:
    plural: pictures
    singular: picture
    kind: Picture
