apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: podcustomizers.kuberneddies.dev
spec:
  group: kuberneddies.dev
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                promote:
                  type: boolean
            status:
              type: object
              properties:
                numPromoted:
                  type: integer
                numDestroyed:
                  type: integer
                observedGeneration:
                  type: integer
                  format: int64
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: promoted
          type: boolean
          jsonPath: .spec.promoted
        - name: numPromoted
          type: integer
          jsonPath: .status.numPromoted
        - name: numDestroyed
          type: integer
          jsonPath: .status.numDestroyed
  scope: Namespaced
  names:
    plural: podcustomizers
    singular: podcustomizer
    kind: PodCustomizer
